### ISSUE TITLE
file_get_contents error

### ISSUE THREAD

**Issue by big89** [Wangoviridans/tesseract-ocr-for-php#2]
Hello there,

I have build a small app on my linux shared server and wamp server on local machine also with this class. I had a lot of issues.
Now i am trying to put my app online on a linux server and i have an issue that is hard to fix.
When i run the script with command line it works perfectly but on browser it says: 

Warning: file_get_contents(temp/1135767769.txt): failed to open stream: No such file or directory in /home/catchmyd/public_html/ocr_demo/TesseractOCR/TesseractOCR.php on line 255

Warning: unlink(temp/1135767769.txt): No such file or directory in /home/catchmyd/public_html/ocr_demo/TesseractOCR/TesseractOCR.php on line 268

I have tried some of tricks discussed here but non of them worked for me.

Regards
big89

**Comment by Wangoviridans** [comment]
As first, sorry for my bad english, I work on it.
It seems what "temp" directory doesn't exists or script doesn't have permission to write in it. Please check the path and it permissions.

**Comment by Wangoviridans** [comment]
FYI, you can specify the "temp" when calling new instance of TesseractOCR class. Just declare "temp" key with right path.
Example: $ocr = new TesseractOCR(array("temp" => "/path/to/temp/")); 

By default it uses http://php.net/manual/en/function.sys-get-temp-dir.php to get temp path.

**Comment by big89** [comment]
Check this is my code -

require_once 'TesseractOCR/TesseractOCR.php';

$path = getenv('PATH');
putenv("PATH=$path:/usr/local/bin");

$tesseract = new TesseractOCR('image.jpg');
$tesseract->setTempDir('temp');
$tesseract->setWhitelist(range(0,9)); //you can pass as many ranges as you need
echo $tesseract->recognize();

am running above code. also i set correct path for 'temp' directory but still its not working.

check and provide corrections. its very urgent for me.

**Comment by Wangoviridans** [comment]
Did you check temp permissions? ( chmod 777 /home/catchmyd/public_html/ocr_demo/temp )

Try to provide full path to temp directory.

$tess = new TesseractOCR();
$tess->setImage('image.jpg');
$tess->setTempDir('/home/catchmyd/public_html/ocr_demo/temp');
etc...

**Comment by big89** [comment]
I already done all this settings. Try to understand my problem what am telling. 

we got following warnings -

Warning: file_get_contents(/home/catchmyd/public_html/ocr_demo/temp/1786607178.txt): failed to open stream: No such file or directory in /home/catchmyd/public_html/ocr_demo/TesseractOCR/TesseractOCR.php on line 255

Warning: unlink(/home/catchmyd/public_html/ocr_demo/temp/1786607178.txt): No such file or directory in /home/catchmyd/public_html/ocr_demo/TesseractOCR/TesseractOCR.php on line 268

Tell me how i can solve this?

**Comment by big89** [comment]
The main important problem is .txt file is not generating using this script. So kindly look into that. its very urgent for me. thanks
